### Question 1

Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.


In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
np.vander(a,increasing=True)
#np.vander(a,N=3)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [2]:
np.vander(a,N=3,increasing=True) #Number of columns in the output. If N is not specified, a square array is returned 

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

### Question 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 

The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 

i 1 2 3 4 5 6 7 8 9 10 

===== == == == == == == == == == == 

Input 10 20 30 40 50 60 70 80 90 100  

y1 25 = (10+20+30+40)/4 

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [8]:
import numpy as np
def moving_average(list, n=3) :
    ret = np.cumsum(list, dtype=float) # to get the cumulative sum of the numbrs
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [21]:
np.cumsum(list, dtype=float)

array([  3.,   8.,  15.,  17.,  25.,  35.,  46., 111., 183., 264., 363.,
       463., 613.])

In [20]:
list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
np.array(moving_average(list, n=3).round(3))

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])